name: CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -f AwesomePasswordChecker/pom.xml clean install

      # - name: Build and Deploy to GitHub Maven Registry
      #   run: |
      #     mvn clean deploy -P release

      - name: Deploy Documentation to GitHub Pages
        run: |
          mvn site -f AwesomePasswordChecker/pom.xml
        # mvn deploy:site

      - name: Generate Cobertura Report
        run: mvn cobertura:cobertura -f AwesomePasswordChecker/pom.xml

      - name: Deploy Cobertura Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/cobertura-report  # Path to the Cobertura report directory