name: CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          java-package: jdk
          distribution: 'adoptopenjdk'  # or 'zulu', 'oracle', etc.
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and Deploy to GitHub Maven Registry
        run: |
          mvn clean deploy -P release

      - name: Deploy Documentation to GitHub Pages
        run: |
          mvn site
          mvn deploy:site

      - name: Deploy Cobertura Report to GitHub Pages
        run: |
          mvn cobertura:cobertura
          mvn site:deploy -DsiteUrl=https://your-username.github.io/repository-name/cobertura/${{ github.run_number }}
