name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run Checkstyle
        run: mvn checkstyle:check

  unit_tests:
    runs-on: ubuntu-latest
    needs: checkstyle
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run Unit Tests
        run: mvn test

  coverage:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run Jacoco Code Coverage
        run: mvn clean verify jacoco:report

      - name: Check Coverage Threshold
        run: |
          COVERAGE=$(mvn jacoco:report-aggregate | grep -o 'Total.*' | grep -o '[0-9]*\.[0-9]*')
          if [ $(echo "$COVERAGE > 90" | bc -l) -ne 1 ]; then
            echo "Coverage is below 90%, current coverage: $COVERAGE"
            exit 1
          fi

  performance_tests:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run Performance Tests
        run: mvn verify -P performance

  sast_scan:
    runs-on: ubuntu-latest
    needs: performance_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep (Static Analysis)
        run: |
          curl -s https://semgrep.dev/install | bash
          semgrep --config=auto
